N = 3;
Dim = N;
LVecs = 1;
GraphObj = HypCub(Dim,'PBC',LVecs,1);
Nb = N; Nmax = 2;
HilbertObj = Bose(N,Nb,Nmax);
Alpha = 3;
ModParams.Nh = Alpha * N; ModParams.a = 0; ModParams.b = 0; ModParams.W = -0.01;
ModParams.nmag = 0.1; ModParams.nphs = 0; ModParams.A = -0.1; ModParams.B = -0.01;
CPSTIObj = CPSTI(HilbertObj,GraphObj,ModParams,1);
Cfg = HilbertObj.RandomCfg();
CPSTIObj = CPSTIObj.PrepPsi(Cfg);
dlogP = CPSTIObj.LogDeriv(Cfg);
%paramlist = CPSTIObj.ParamList();
%dP = 2.0 * ones(44,1);
%CPSTIObj = CPSTIObj.updateCPSTI(dP);
